[package]
name = "termctl"
version = "0.1.2"
edition = "2024"
readme = "README.md"
description = "small crate for controlling terminal output"
repository = "https://github.com/amos-tg/termctl"
license = "MIT OR Apache-2.0"
